#/bin/sh
function tmux_connect() {
  tmux new-window -k -t FPU0:$3 -n $1  "rsync /home/admin/screenrc $2:/home/admin/screenrc ; ssh $2 -t screen -d -R FPU0 -c /home/admin/screenrc " 
}
tmux new-session -s FPU0 -n main -d
tmux_connect servermdb1 servermdb1.local 1 1
tmux_connect servermdb2 servermdb2.local 2 1
tmux_connect servercolodepot1 servercolodepot1.local 3 1
tmux_connect servercolodepot2 servercolodepot2.local 4 1
tmux_connect servercolodepot3 servercolodepot3.local 5 1
tmux_connect serverdepot1 serverdepot1.local 6 1
tmux_connect serverdepot2 serverdepot2.local 7 1
tmux_connect serverdepot3 serverdepot3.local 8 1
tmux_connect servergw1 servergw1.local 9 1
tmux_connect servergw2 servergw2.local 10 1
tmux_connect servergw3 servergw3.local 11 1
tmux_connect serverrig1 serverrig1.local 12 1
tmux_connect serverrig2 serverrig2.local 13 1
tmux_connect servertmpdepot1 servertmpdepot1.local 14 1
tmux_connect servertmpdepot2 servertmpdepot2.local 15 1
tmux_connect serverwagw1 serverwagw1.local 16 1
tmux_connect serverwagw2 serverwagw2.local 17 1
tmux_connect serveralmod1 serveralmod1.local 18 1
tmux_connect serverbamod1 serverbamod1.local 19 1
tmux_connect serverbhmod1 serverbhmod1.local 20 1
tmux_connect serverbrmod1 serverbrmod1.local 21 1
tmux_connect serverbwmod1 serverbwmod1.local 22 1
tmux_connect servercfmod1 servercfmod1.local 23 1
tmux_connect serverclmod1 serverclmod1.local 24 1
tmux_connect servercnmod1 servercnmod1.local 25 1
tmux_connect servercwmod1 servercwmod1.local 26 1
tmux_connect servercymod1 servercymod1.local 27 1
tmux_connect serverdamod1 serverdamod1.local 28 1
tmux_connect serveregmod1 serveregmod1.local 29 1
tmux_connect serverfomod1 serverfomod1.local 30 1
tmux_connect serverfrmod1 serverfrmod1.local 31 1
tmux_connect serverftmod1 serverftmod1.local 32 1
tmux_connect servering1 servering1.local 33 1
tmux_connect servering2 servering2.local 34 1
tmux_connect servering3 servering3.local 35 1
tmux_connect servering4 servering4.local 36 1
tmux_connect servering5 servering5.local 37 1
tmux_connect servering6 servering6.local 38 1
tmux_connect servermamod1 servermamod1.local 39 1
tmux_connect servermimod1 servermimod1.local 40 1
tmux_connect servermod1 servermod1.local 41 1
tmux_connect servermod2 servermod2.local 42 1
tmux_connect servermod3 servermod3.local 43 1
tmux_connect servermod4 servermod4.local 44 1
tmux_connect servermon1 servermon1.local 45 1
tmux_connect servermrmod1 servermrmod1.local 46 1
tmux_connect servermvmod1 servermvmod1.local 47 1
tmux_connect servernimod1 servernimod1.local 48 1
tmux_connect serveropmod1 serveropmod1.local 49 1
tmux_connect serversnmod1 serversnmod1.local 50 1
tmux_connect serverspmod1 serverspmod1.local 51 1
tmux_connect serversymod1 serversymod1.local 52 1
tmux_connect servervemod1 servervemod1.local 53 1
tmux_connect servervicbormod1 servervicbormod1.local 54 1
tmux_connect serverviccarmod1 serverviccarmod1.local 55 1
tmux_connect serverviccramod1 serverviccramod1.local 56 1
tmux_connect servervicdanmod1 servervicdanmod1.local 57 1
tmux_connect servervicelsmod1 servervicelsmod1.local 58 1
tmux_connect servervicframod1 servervicframod1.local 59 1
tmux_connect servervicsommod1 servervicsommod1.local 60 1
tmux_connect servervpmod1 servervpmod1.local 61 1
tmux_connect serverwabgmod1 serverwabgmod1.local 62 1
tmux_connect serverwabsmod1 serverwabsmod1.local 63 1
tmux_connect serverwacmmod1 serverwacmmod1.local 64 1
tmux_connect serverwaeamod1 serverwaeamod1.local 65 1
tmux_connect serverwaelmod1 serverwaelmod1.local 66 1
tmux_connect serverwafrmod1 serverwafrmod1.local 67 1
tmux_connect serverwairmod1 serverwairmod1.local 68 1
tmux_connect serverwaqumod1 serverwaqumod1.local 69 1
tmux_connect serverweb1 serverweb1.local 70 1
tmux_connect serverweb2 serverweb2.local 71 1
tmux_connect serverwemod1 serverwemod1.local 72 1
tmux_connect serverwpmod1 serverwpmod1.local 73 1
tmux_connect serverzzmod1 serverzzmod1.local 74 1
tmux_connect serverzzweb1 serverzzweb1.local 75 1
tmux_connect serverzzweb2 serverzzweb2.local 76 1
tmux a -t FPU0
